FiverrIntelligensePortal/FiverrIntelligense/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FiverrIntelligense.Data.Common;
using FiverrIntelligense.Data.Models;
using FiverrIntelligense.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FiverrIntelligense.Controllers
{
    [Authorize]
    public class HistoryController : Controller
    {
        IGroupService _groupService;
        IKeywordService _keywordService;
        IUserKeywordService _userKeywordService;
        public HistoryController(IGroupService groupService, IKeywordService keywordService, IUserKeywordService UserKeywordService)
        {
            _groupService = groupService;
            _keywordService = keywordService;
            _userKeywordService = UserKeywordService;
        }
        public IActionResult Index()
        {
            Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
            List<TblFiverrGroup> lstGfoup = _groupService.GetAllGroupsOfUsr(userId).OrderBy(x => x.GroupName).ToList();
            List<SelectListItem> myGroups = new List<SelectListItem>();
           
            foreach (var item in lstGfoup)
            {
                myGroups.Add(new SelectListItem
                {
                    Text = item.GroupName,
                    Value = item.GroupId.ToString()
                });
            }
            ViewBag.AllGroups = myGroups;
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            return View();
        }

        public ActionResult GetAllDataForGrid(string groupId, string startDate, string endDate)
        {
            List<HistoryViewModel> historyViewModels = new List<HistoryViewModel>();
            try
            {
                // code to get data from database
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                historyViewModels = _groupService.GetAllHistory(userId, groupId,startDate,endDate).OrderBy(x => x.BussinesGroup).ToList();
            }
            catch (Exception ex)
            {
                throw;
            }
            return PartialView("_historyPartial", historyViewModels);
        }
    }
}

FiverrIntelligensePortal/FiverrIntelligense/Controllers/KeywordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FiverrIntelligense.Data.Models;
using FiverrIntelligense.Models;
using FiverrIntelligense.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace FiverrIntelligense.Controllers
{
    //[Authorize]
    public class KeywordController : Controller
    {
        IGroupService _groupService;
        IKeywordService _keywordService;
        IUserKeywordService _userKeywordService;
        public KeywordController(IGroupService groupService, IKeywordService keywordService, IUserKeywordService UserKeywordService)
        {
            _groupService = groupService;
            _keywordService = keywordService;
            _userKeywordService = UserKeywordService;
        }
        public IActionResult Index()
        {
            Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
            List<TblFiverrGroup> lstGfoup = _groupService.GetAllGroupsOfUsr(userId).ToList();
            List<SelectListItem> myGroups = new List<SelectListItem>();
            if (lstGfoup.Count > 0)
            {
                foreach (var item in lstGfoup)
                {
                    myGroups.Add(new SelectListItem
                    {
                        Text = item.GroupName,
                        Value = item.GroupId.ToString()
                    });
                }
            }
            ViewBag.AllGroups = myGroups;
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            return View();
        }

        public string GetAllKeywordsDetails(string GroupId)
        {
            if (!string.IsNullOrEmpty(GroupId))
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));

                var lstKeyword = _keywordService.GetAllKeywordOfUserGroup(userId, GroupId).OrderBy(x => x.KeywordName).ToList();
                if (lstKeyword != null)
                {
                    return JsonConvert.SerializeObject(lstKeyword);
                }
            }
            return "";
        }
        public string GetAllKeywordsDetailsOfAllGroups()
        {
            Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
            List<TblFiverrGroup> lstGroup = _groupService.GetAllGroupsOfUsr(userId).OrderBy(x => x.GroupName).ToList();
            List<GroupWithAllKeywords> lstAllGroupWithKeeywords = new List<GroupWithAllKeywords>();
            foreach (var grp in lstGroup)
            {
                GroupWithAllKeywords tempObj = new GroupWithAllKeywords()
                {
                    GroupId = grp.GroupId,
                    GroupName = grp.GroupName,
                    lstKeyword = _keywordService.GetAllKeywordOfUserGroup(userId, grp.GroupId.ToString()).OrderBy(x => x.KeywordName).ToList()
                };
                lstAllGroupWithKeeywords.Add(tempObj);
            }
            return JsonConvert.SerializeObject(lstAllGroupWithKeeywords);
        }
        public string GetAllKeywordsOfGroup(string GroupId)
        {
            var lstKeyword = _keywordService.GetAll().Where(x => x.GroupId == Convert.ToInt32(GroupId)).ToList();
            if (lstKeyword != null)
            {
                return JsonConvert.SerializeObject(lstKeyword);
            }
            return "";
        }
        public string GetAllGroupsAndKeywords()
        {
            return JsonConvert.SerializeObject(new { Groups = _groupService.GetAll().ToList(), Keywords = _keywordService.GetAll().ToList() });
        }
        [HttpPost]
        public string AddKeyword(string keywordName, string groupId)
        {
            try
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                var keyword = _keywordService.GetAll().Where(x => x.KeywordName.ToLower() == keywordName.ToLower()).FirstOrDefault();
                if (keyword == null)
                {
                    _keywordService.Insert(new TblFiverrKeyword()
                    {
                        GroupId = Convert.ToInt32(groupId),
                        KeywordName = keywordName,
                        CreatedOn = DateTime.Now,
                        UpdatedOn = DateTime.Now.ToString()
                    });
                    _keywordService.Save();
                    keyword = _keywordService.GetAll().Where(x => x.KeywordName.ToLower() == keywordName.ToLower()).FirstOrDefault();
                }
                var keyMap = _userKeywordService.GetAll().Where(x => x.UserId == userId && x.KeywordID == keyword.KeywordID).FirstOrDefault();
                if (keyMap == null)
                {
                    _userKeywordService.Insert(new TblUserKeywordMap()
                    {
                        UserId = userId,
                        KeywordID = keyword.KeywordID
                    });
                    _userKeywordService.Save();
                }
                else
                {
                    keyMap.IsActive = 1;
                    _userKeywordService.Update(keyMap);
                    _userKeywordService.Save();
                }
                return "success";
            }
            catch (Exception)
            {
            }
            return "";
        }
        [HttpPost]
        public string RemoveKeywordFromGroup(string keywordId)
        {
            try
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                var existingKey = _userKeywordService.GetAll().Where(x => x.KeywordID == Convert.ToInt32(keywordId) && x.UserId == userId && x.IsActive == 1).FirstOrDefault();
                if (existingKey != null)
                {
                    //_userKeywordService.Delete(existingKey.Id);
                    existingKey.IsActive = 0;
                    _userKeywordService.Update(existingKey);
                    _userKeywordService.Save();
                    return "success";
                }
                return "Key word not found.";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

        }

        [HttpPost]
        public string EditKeyword(string KeywordID, string keywordName)
        {
            try
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                var existingKey = _keywordService.GetAll().Where(x => x.KeywordID == Convert.ToInt32(KeywordID)).FirstOrDefault();
                if (existingKey != null)
                {
                    existingKey.KeywordName = keywordName;
                    _keywordService.Update(existingKey);
                    _keywordService.Save();
                    return "success";
                }
                return "Key word not found.";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

        }
    }
}

FiverrIntelligensePortal/FiverrIntelligense/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FiverrIntelligense.Data.Common;
using FiverrIntelligense.Data.Models;
using FiverrIntelligense.Services.IServices;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace FiverrIntelligense.Controllers
{
    public class StatusController : Controller
    {
        IGroupService _groupService;
        IKeywordService _keywordService;
        IUserKeywordService _userKeywordService;
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _env;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ISession _session;
        public StatusController(IGroupService groupService, IKeywordService keywordService, IUserKeywordService UserKeywordService, IConfiguration configuration, IWebHostEnvironment env, IHttpContextAccessor httpContextAccessor)
        {
            _groupService = groupService;
            _keywordService = keywordService;
            _userKeywordService = UserKeywordService;
            _configuration = configuration;
            _env = env;
            _httpContextAccessor = httpContextAccessor;
            _session = _httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Index()
        {
            return View();
        }

        public string GetKeywodsRunningStatus(string keywords)
        {
            string result = "";
            try
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                List<KeywordRunningStatus> lstResult = new List<KeywordRunningStatus>();
                lstResult = _keywordService.GetKeywodsRunningStatus(userId, keywords);
                result = JsonConvert.SerializeObject(lstResult);
            }
            catch (Exception ex)
            {
                throw;
            }
            return result;
        }

        public string GetKeywordProgressCount(string keywords)
        {
            string result = "";
            try
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                List<KeywordProgressCount> lstResult = new List<KeywordProgressCount>();
                lstResult = _keywordService.GetKeywordProgressCount(userId, keywords);
                result = JsonConvert.SerializeObject(lstResult);
            }
            catch (Exception ex)
            {
                throw;
            }
            return result;
        }

        #region Rolling Chart
        public string GetKeywordByGroupOfUser()
        {
            string result = "";
            try
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                List<TblFiverrGroup> lstGroup = _groupService.GetAllGroupsOfUsr(userId);
                List<Keyword> lstKeyword;
                foreach (var group in lstGroup)
                {
                    lstKeyword = _keywordService.GetKeywordByGroup(userId, group.GroupId);
                    result = JsonConvert.SerializeObject(lstKeyword);
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return result;
        }

        public void RunFiverrExeForKeywords(string keywordIds)
        {
            try
            {
                if (!string.IsNullOrEmpty(keywordIds))
                {
                    HttpContext.Session.SetString("KeywordIds", keywordIds.TrimEnd(','));
                    string[] keywordIdds = keywordIds.TrimEnd(',').Split(",");
                    if (keywordIdds.Length > 0)
                    {
                        foreach (var keywordId in keywordIdds)
                        {
                            if (!string.IsNullOrEmpty(keywordId))
                            {
                                string keyword = string.Format("KeywordID:{0}", Convert.ToInt32(keywordId));
                                try
                                {
                                    System.Diagnostics.Process.Start(_configuration.GetValue<string>("FiverrScrapper"), keyword);
                                    HttpContext.Session.SetString("isKeywordRunning", "true");
                                }
                                catch (Exception ex)
                                {
                                    throw;
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
        public string GetRollingData(string keywordIds)
        {
            var result = "";
            try
            {
                int IsKeywordCompleted = 0;
                RollingData objRollingData = new RollingData();
                List<RollingData> lstRollingData = new List<RollingData>();
                Guid userId = Guid.Parse(HttpContext.Session.GetString("UserId"));
                int secDifference = _configuration.GetValue<int>("SecondDifference");
                if (!string.IsNullOrEmpty(keywordIds))
                {
                    string[] keywordIdds = keywordIds.TrimEnd(',').Split(",");
                    if (keywordIdds.Length > 0)
                    {
                        foreach (var keywordID in keywordIdds)
                        {
                            if (!string.IsNullOrEmpty(keywordID))
                            {
                                objRollingData = _keywordService.GetRollingData(userId, Convert.ToInt32(keywordID), secDifference);
                                if (objRollingData != null)
                                {
                                    lstRollingData.Add(objRollingData);
                                    if (objRollingData.Status == "Completed")
                                    {
                                        IsKeywordCompleted++;
                                    }
                                    if (keywordIdds.Length == IsKeywordCompleted)
                                    {
                                        HttpContext.Session.SetString("isKeywordCompleted", "false");
                                    }
                                }
                            }
                        }
                        result = JsonConvert.SerializeObject(lstRollingData);
                    }
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return result;
        }
        #endregion
    }
}

FiverrIntelligensePortal/FiverrIntelligense/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
    <link href="~/MainJs/Charts/Chart.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" media="all" href="~/dateRange/daterangepicker.css" />
    <link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css" rel="stylesheet" />
    <link href="~/assets/styles/index.css" rel="stylesheet" />

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <style>
        #loader {
            transition: all 0.3s ease-in-out;
            opacity: 1;
            visibility: visible;
            position: fixed;
            height: 100vh;
            width: 100%;
            background: #ffffff73;
            z-index: 90000;
        }

            #loader.fadeOut {
                opacity: 0;
                visibility: hidden;
            }

        .spinner {
            width: 100px;
            height: 100px;
            position: absolute;
            top: calc(50% - 20px);
            left: calc(50% - 20px);
            background-color: #333;
            border-radius: 100%;
            -webkit-animation: sk-scaleout 1.0s infinite ease-in-out;
            animation: sk-scaleout 1.0s infinite ease-in-out;
        }

        @@-webkit-keyframes sk-scaleout {
            0% {
                -webkit-transform: scale(0)
            }

            100% {
                -webkit-transform: scale(1.0);
                opacity: 0;
            }
        }

        @@keyframes sk-scaleout {
            0% {
                -webkit-transform: scale(0);
                transform: scale(0);
            }

            100% {
                -webkit-transform: scale(1.0);
                transform: scale(1.0);
                opacity: 0;
            }
        }
        .dataTable th, .dataTable td {
            padding: 0.3rem;
        }
    </style>
    <style>
        .multiselect-container > li > a > label.checkbox {
            width: 100%;
            padding-left:15px;
        }

        button.multiselect.dropdown-toggle.btn.btn-default {
            border: 2px solid #cccccc;
        }
        .multiselect-container > li > a > label > input[type=checkbox] {
            opacity: 1;
        }

        .toast-success {
            background-color: #51A351 !important;
        }

        .toast-error {
            background-color: #BD362F !important;
        }

        .toast-info {
            background-color: #2F96B4 !important;
        }

        .toast-warning {
            background-color: #F89406 !important;
        }

    </style>
    
    @RenderSection("Styles", required: false)
</head>
<body class="app">

    <div id='loader'>
        <div class="spinner"></div>
    </div>

    <script>
        window.addEventListener('load', function load() {
            const loader = document.getElementById('loader');
            setTimeout(function () {
                loader.classList.add('fadeOut');
            }, 10000);
        });
    </script>
    <div>
        <!-- #Left Sidebar ==================== -->
        <div class="sidebar">
            <div class="sidebar-inner">
                <!-- ### $Sidebar Header ### -->
                <div class="sidebar-logo">
                    <div class="peers ai-c fxw-nw">
                        <div class="peer peer-greed">
                            <a class="sidebar-link td-n" href="index.html">
                                <div class="peers ai-c fxw-nw">
                                    <div class="peer">
                                        <div class="logo">
                                            <img src="~/assets/static/images/logo.png" alt="">
                                        </div>
                                    </div>
                                    <div class="peer peer-greed">
                                        <h5 class="lh-1 mB-0 logo-text">Fiverr Intelligence</h5>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="peer">
                            <div class="mobile-toggle sidebar-toggle">
                                <a href="" class="td-n">
                                    <i class="ti-arrow-circle-left"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- ### $Sidebar Menu ### -->
                <ul class="sidebar-menu scrollable pos-r">
                    <li class="nav-item mT-30 active">
                        <a class="sidebar-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                            <span class="icon-holder">
                                <i class="c-blue-500 ti-home"></i>
                            </span>
                            <span class="title">My Dashboard</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class='sidebar-link' asp-area="" asp-controller="Keyword" asp-action="Index">
                            <span class="icon-holder">
                                <i class="c-deep-purple-500 ti-comment-alt"></i>
                            </span>
                            <span class="title">Keywords</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class='sidebar-link' asp-area="" asp-controller="Status" asp-action="Index">
                            <span class="icon-holder">
                                <i class="c-deep-orange-500 ti-calendar"></i>
                            </span>
                            <span class="title">Keywords Status</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class='sidebar-link' asp-area="" asp-controller="History" asp-action="Index">
                            <span class="icon-holder">
                                <i class="c-indigo-500 ti-bar-chart"></i>
                            </span>
                            <span class="title">Check Keyword History</span>
                        </a>
                    </li>

                </ul>
            </div>
        </div>

        <!-- #Main ============================ -->
        <div class="page-container">
            <!-- ### $Topbar ### -->
            <div class="header navbar">
                <div class="header-container">
                    <ul class="nav-left">
                        <li>
                            <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
                                <i class="ti-menu"></i>
                            </a>
                        </li>
                        <li class="search-box">
                            <a class="search-toggle no-pdd-right" href="javascript:void(0);">
                                <i class="search-icon ti-search pdd-right-10"></i>
                                <i class="search-icon-close ti-close pdd-right-10"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav-right">
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
                                <div class="peer mR-10">
                                    @*<img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/10.jpg" alt="">*@
                                    <i class="w-2r bdrs-50p ti-user" style="font-size:25px;"></i>                                 
                                </div>
                                <div class="peer">
                                    <span class="fsz-sm c-grey-900">@ViewBag.UserName</span>
                                </div>
                            </a>
                            <ul class="dropdown-menu fsz-sm">
                                @*<li>
                                        <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                            <i class="ti-settings mR-10"></i>
                                            <span>Setting</span>
                                        </a>
                                    </li>*@
                                <li>
                                    <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                        <i class="ti-user mR-10"></i>
                                        <span>Profile</span>
                                    </a>
                                </li>
                                @*<li>
                                        <a href="email.html" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                            <i class="ti-email mR-10"></i>
                                            <span>Messages</span>
                                        </a>
                                    </li>*@
                                <li role="separator" class="divider"></li>
                                <li>
                                    <a href="/account/Logout" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                        <i class="ti-power-off mR-10"></i>
                                        <span>Logout</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- ### $App Screen Content ### -->
            <main class='main-content bgc-grey-100'>
                <div id='mainContent'>
                    @RenderBody()
                </div>
            </main>

        </div>
    </div>
    <span class="chart" data-percent="86">
        <span class="percent"></span>
    </span>
    <footer class="border-top footer text-muted">
        @*<div class="container">
                &copy; 2020 - Amazon - MAS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>*@
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/MainJs/Charts/colors.js"></script>
    <script src="~/MainJs/Charts/Chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="~/MainJs/Charts/jquery.easypiechart.js"></script>
    <script src="~/MainJs/Charts/jquery.sparkline.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>
    <script type="text/javascript" src="~/dateRange/daterangepicker.js"></script>
    <script type="text/javascript" src="~/dateRange/dateRangejs.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/js/bootstrap-multiselect.min.js" integrity="sha256-qoj3D1oB1r2TAdqKTYuWObh01rIVC1Gmw9vWp1+q5xw=" crossorigin="anonymous"></script>
    <script>
        // ٍSidebar Toggle
        $('.sidebar-toggle').on('click', e => {
            $('.app').toggleClass('is-collapsed');
            e.preventDefault();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>